---
title: "My Academic and Professional Experience"
output: 
  html_document:
    toc: true
    toc_float: true
---

#This page includes infortmation on my academic and professional experience 

RESEARCH EXPERIENCE  

Harvard T.H. Chan School of Public Health Summer Program in Epidemiology and Biostatistics, Cambridge 
MA                                                                                         06/2021-07/2021 
•	Conducted a research project where we looked at the distribution of genomic surveillance for Covid-19 and sequencing delays in the United States and surrounding territories 
•	Collected Covid-19 case list from the Centers for Disease Control and Prevention (CDC) and analyzed the distributions of identified positive cases 
•	Gathered epidemiological data of each sequence in the GISAID isolated from the US to analyze the temporal and geographical distributions of these sequences 
•	Learned how to calculate and determined the sequencing delays (by days) and representativeness of genomic surveillance by calculating the percentage of sequenced samples in each state and territory 
•	Evaluated missing data in the case list and sequenced data in order to see any aspects that can be improved 
•	Worked on R programming skills and learned how to calculate descriptive statistics and perform mathematical modeling 
•	Took Introduction to Epidemiology, Introduction to Biostatistics Course
•	Research Mentor: Dr. Xueting Qiu 


NYU Diversity Undergraduate Research Incubator, New York, NY Research Mentee   	       06/2019-07/2019  
•	Worked in Primate Reproductive Ecology and Evolution Laboratory  
•	Performed Polymerase Chain Reaction (PCR) and learned how to pipet DNA from species of primates  
•	Used software known as GENEIOUS to align and edit different DNA sequences among thirty primate species  
•	Learned how to use PAML computer programming software to find the dN/dS ratio  
•	Research Mentor: Dr. Alexandra Decasien  
GENESIS Scientific Research Program - St. John the Baptist Diocesan High School, West Islip, NY 05/2015-05/2018 Researcher  
•	Assisted presenters at the second Genesis annual symposium  
•	Conducted a research study on ligament injuries in high school students  
•	Presented the study about ligament injuries on high school students at the third Genesis annual symposium  



PROFESSIONAL DEVELOPMENT AND LEADERSHIP 
OP Ambassador, Opportunity Program                                                      10/12/2019-3/10/2020 
•	Hosted events for students in the Opportunity Program such as Luncheon during Finals week, resume workshops, business etiquette, and the Opportunity Program Admissions Collegiate Admissions Tour 
•	Spoke with prospective OP students and parents about the benefits of the program 


Grant Writing Experience  
•	Wrote grant to purchase PCR primer for five different species of anthropoids from NCBI database and purchased sequencing for these species. Also sought and secured funding for transportation to travel to and from the NYU Department of Anthropology Laboratory to participate in the project.  This grant was submitted during the DURI program, and I was awarded $937.00.  
•	Advisor: Dr. Alexandra Decasien 
•	Wrote a second grant proposal to secure access to the Dean’s Undergraduate Research Fund (DURF) to continue the research project begun during the DURI program.  Sought additional funding to purchase a one-year GENEIOUS subscription, more PCR primers, supplies for PCR, gel electrophoresis, whole genomes, and amplification kit 
•	Advisors:  Dr. James Higham and Dr. Alexandra Decasien 


How to Manage a Small Law Firm Seminar - San Antonio, TX   	 	                                      01/18/2019-01/22/2019
Intern at the Law Offices of Marjory Cajoux  

•	Trained in calculating the value of a small law firm  
•	Gained knowledge about leadership skills and Key Performance Indicators (KPIs) for various positions in the workplace  
 
Rule #1 Investing Virtual Workshop   	 	 	 	 	                            08/21/2020-08/23/2020  Student  
•	Learned to create a profile to recognize profitable companies using their filed reports  
•	Used Rule #1 investing toolbox to assess the value of a company and when to enter and exit the market  
•	Learned how to use Thinkorswim trading computer software and performed first simulated PUT trade  
•	Calculated the Future Growth Rate (FGR), Annualized Return on Risk Capital (ARORC), Margin of Safety Price, and 
8-year Payback time price  


WORK EXPERIENCE 

Law Offices of Marjory Cajoux, Brooklyn, NY  	 	 	 	                           06/2013-Present          Summer Intern  
•	Learned and worked on client communication skills 
•	Conducted confidential client communication and sorted and filed sensitive documents 
•	Kept schedules and maintained electronic records and legal books 
•	Prepared meeting agendas  
•	Assisted in courts, at closings, and in depositions  
•	Observed court proceedings  




